version: "3.0"

services:
  user-service:
    container_name: user-service-api
    image: user-service:0.0.1
    ports:
      - 8081:8081
    depends_on:
      - user-services-db
    
  user-review-service:
    container_name: user-review-service-api
    image: user-review-service:0.0.1
    ports:
      - 8083:8083
    depends_on:
      - user-services-db

  restaurant-service:
    container_name: restaurant-service-api
    image: restaurant-service:0.0.1
    ports:
      - 8082:8082
    depends_on:
      - restaurant-db

  logger-service:
    container_name: logger-service-api
    image: logger-service:0.0.1
    ports:
      - 8089:8089
    depends_on:
      - user-services-db
      - zookeeper
      - kafka

  user-services-db:
    container_name: user-services-postgres-db
    image: postgres
    environment:
      POSTGRES_DB: TalentHub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1905
    ports:
      - 5433:5432
    volumes:
      - user-services-db-data:/var/lib/postgresql/data

  logger-service-db:
    container_name: logger-service-postgres-db
    image: postgres
    environment:
      POSTGRES_DB: logger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1905
    ports:
      - 5434:5432
    volumes:
      - logger-service-db-data:/var/lib/postgresql/data

  restaurant-db:
    image: solr:latest
    container_name: restaurant-solr-db
    ports:
      - "8983:8983"
    volumes:
      - restaurant-solr-db-data:/var/solr
    command:
      - solr-precreate
      - n11_restaurants
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  user-services-db-data:
  restaurant-solr-db-data:
  logger-service-db-data:
